name: Unit tests

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
    - 'github-actions'

jobs:
  tests:
    run-on: windows-latest #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: tests
        run: npm test