export const SIGNAL_TYPE = {
  BOT_AI: 'BOT_AI',
  TELEGRAM: 'TELEGRAM',
  EXPERT: 'EXPERT',
  PATTERN: 'PATTERN',
};
export const SIGNAL_METHOD = {
  STRING: 'STRING_METHOD',
  MIX: 'MIX_METHOD',
  SINGLE: 'SINGLE_METHOD',
};
