export enum SETTINGS {
  OPEN_SIDEBAR = 'OPEN_SIDEBAR',
  CLOSE_SIDEBAR = 'CLOSE_SIDEBAR',
  OPEN_HEADER = 'OPEN_HEADER',
  OPEN_SIDEBAR_AND_HEADER = 'OPEN_SIDEBAR_AND_HEADER',
  CLOSE_SIDEBAR_AND_HEADER = 'CLOSE_SIDEBAR_AND_HEADER',
  OPEN_LOADING = 'OPEN_LOADING',
  CLOSE_LOADING = 'CLOSE_LOADING',
}

export interface SettingsState {
  sideBarOpen: boolean;
  headerOpen: boolean;
  loading: boolean;
}
