name: Unit tests

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
    branches:
      - 'github-actions'

jobs:
  backend:
    runs-on: ubuntu-latest 
    #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    defaults:
      run:
        working-directory: ./back-end

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Clone Submodule #https://rgoswami.me/posts/priv-gh-actions/
        env:
          SSHK: ${{ secrets.SUB_CREDENTIALS }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSHK" > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          git submodule update --init --recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Run test
        run: npm test
  frontend:
    runs-on: ubuntu-latest 
    #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    defaults:
      run:
        working-directory: ./front-end

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Run test
        run: npm test
  Deploy-Heroku:
    # https://arctype.com/blog/github-vercel/
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Clone Submodule #https://rgoswami.me/posts/priv-gh-actions/
        env:
          SSHK: ${{ secrets.SUB_CREDENTIALS }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSHK" > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          git submodule update --init --recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Login to Heroku Container registry
        run: heroku container:login 
